from .test_routes import test_routes
from .job_listing_routes import job_listing_routes
from .saved_job_routes import saved_job_routes
from .scraped_site_routes import scraped_site_routes
from .auth_routes import auth_routes
from .user_routes import user_routes
from .application_stage_routes import application_stage_routes
from .contact_routes import contact_routes
from .task_routes import task_routes
from .document_routes import document_routes
from .document_type_routes import document_type_routes
from .notification_routes import notification_routes