"""add task table field: is_reminded

Revision ID: 0fbcb42372b2
Revises: d3f3d2ddd587
Create Date: 2024-02-03 10:05:38.930176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fbcb42372b2'
down_revision = 'd3f3d2ddd587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reminded', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('is_reminded')

    # ### end Alembic commands ###
