"""Removed reminder_date field from tasks table

Revision ID: 186ae3ffb9a4
Revises: 9d5aed109696
Create Date: 2024-02-15 09:41:34.823717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '186ae3ffb9a4'
down_revision = '9d5aed109696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('reminder_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_date', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
