"""update tasks table

Revision ID: 236e85e0fdd7
Revises: d01c1cab43c2
Create Date: 2024-01-20 12:07:37.025473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '236e85e0fdd7'
down_revision = 'd01c1cab43c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_notify_on_website', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_notify_notification')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_notify_notification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('is_notify_on_website')

    # ### end Alembic commands ###
