"""modify application_stage table

Revision ID: 666a2c1b22fe
Revises: fa483d9a4b99
Create Date: 2024-01-12 11:20:46.510138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '666a2c1b22fe'
down_revision = 'fa483d9a4b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_stages', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', mysql.VARCHAR(length=150), nullable=False))

    # ### end Alembic commands ###
