"""Update Document table

Revision ID: 67d295dd30f2
Revises: cb8eff2f305d
Create Date: 2024-01-27 23:00:04.687134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d295dd30f2'
down_revision = 'cb8eff2f305d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('file_url', sa.String(length=500), nullable=False))
        batch_op.drop_column('document_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_name', mysql.VARCHAR(length=150), nullable=False))
        batch_op.drop_column('file_url')
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
