"""Add created_at field saved_job table

Revision ID: 75a6a8e4310f
Revises: 99db80fa52d2
Create Date: 2024-01-30 20:17:26.682482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a6a8e4310f'
down_revision = '99db80fa52d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
