"""Update saved job table constraints

Revision ID: 933c71e1561d
Revises: 0fbcb42372b2
Create Date: 2024-02-06 21:20:30.961885

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '933c71e1561d'
down_revision = '0fbcb42372b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('additional_info',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('job_url',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)

    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=250),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('job_description',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=6000),
               existing_nullable=True)
        batch_op.alter_column('additional_info',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('job_url',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.alter_column('job_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('additional_info',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('job_description',
               existing_type=sa.String(length=6000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)

    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.alter_column('job_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=False)
        batch_op.alter_column('additional_info',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
