"""Modified notifications and scrape settings table

Revision ID: 9a12e08f207b
Revises: 933c71e1561d
Create Date: 2024-02-12 10:08:52.241984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a12e08f207b'
down_revision = '933c71e1561d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint('notifications_ibfk_1', type_='foreignkey')
        batch_op.drop_column('scraped_site_id')

    with op.batch_alter_table('scraped_site_settings', schema=None) as batch_op:
        batch_op.drop_column('is_scrape_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraped_site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_scrape_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scraped_site_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('notifications_ibfk_1', 'scraped_sites', ['scraped_site_id'], ['id'])

    # ### end Alembic commands ###
