"""Add is_favorite field for saved_job

Revision ID: 9d5aed109696
Revises: 9a12e08f207b
Create Date: 2024-02-12 20:09:01.219652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5aed109696'
down_revision = '9a12e08f207b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_jobs', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###
