"""Update scrapesite setting table

Revision ID: d01c1cab43c2
Revises: 666a2c1b22fe
Create Date: 2024-01-19 11:50:39.644692

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd01c1cab43c2'
down_revision = '666a2c1b22fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraped_site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_notify_on_website', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_notify_notification')
        batch_op.drop_column('work_type')
        batch_op.drop_column('is_notification_enabled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scraped_site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_notification_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('work_type', mysql.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('is_notify_notification', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('is_notify_on_website')

    # ### end Alembic commands ###
