"""Add all tables

Revision ID: d1198cb75421
Revises: 07dd83579a7c
Create Date: 2024-01-06 20:44:43.995151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1198cb75421'
down_revision = '07dd83579a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=150), nullable=False),
    sa.Column('color', sa.String(length=150), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_name', sa.String(length=150), nullable=False),
    sa.Column('scrape_url', sa.String(length=1000), nullable=False),
    sa.Column('is_scrape_enabled', sa.Boolean(), nullable=False),
    sa.Column('scrape_frequency', sa.Integer(), nullable=False),
    sa.Column('is_notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_notify_email', sa.Boolean(), nullable=False),
    sa.Column('is_notify_notification', sa.Boolean(), nullable=False),
    sa.Column('last_scrape_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_site_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('job_description', sa.String(length=1000), nullable=True),
    sa.Column('additional_info', sa.String(length=1000), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=False),
    sa.Column('posted_date', sa.String(length=100), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scraped_site_id'], ['scraped_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scraped_site_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scraped_site_id'], ['scraped_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('job_description', sa.String(length=1000), nullable=True),
    sa.Column('additional_info', sa.String(length=1000), nullable=True),
    sa.Column('job_type', sa.String(length=100), nullable=True),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('job_url', sa.String(length=1000), nullable=False),
    sa.Column('posted_date', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['application_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=150), nullable=False),
    sa.Column('person_position', sa.String(length=150), nullable=True),
    sa.Column('person_linkedin', sa.String(length=250), nullable=True),
    sa.Column('person_email', sa.String(length=250), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['saved_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('document_name', sa.String(length=150), nullable=False),
    sa.Column('date_uploaded', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_type_id'], ['document_types.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['saved_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('task_name', sa.String(length=150), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_date', sa.Integer(), nullable=True),
    sa.Column('is_notify_email', sa.Boolean(), nullable=False),
    sa.Column('is_notify_notification', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['saved_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('documents')
    op.drop_table('contacts')
    op.drop_table('saved_jobs')
    op.drop_table('notifications')
    op.drop_table('job_listings')
    op.drop_table('scraped_sites')
    op.drop_table('document_types')
    op.drop_table('application_stages')
    # ### end Alembic commands ###
