"""Add created_at field for job listing

Revision ID: fa483d9a4b99
Revises: 49ac676ca0bb
Create Date: 2024-01-11 10:31:19.453909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa483d9a4b99'
down_revision = '49ac676ca0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
